name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Cordova
        run: npm install -g cordova
      - name: Install Platform and Plugins
        run: |
          cordova platform add android
          cordova plugin add cordova-plugin-admob-plus --variable APP_ID_ANDROID="ca-app-pub-3498906520872394~3153954244"
      - name: Build APK
        run: cordova build android --debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
